name: Dependency Review

on:
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - '**/package.json'
      - 'requirements.txt'
      - 'requirements-dev.txt'
      - '**/pyproject.toml'

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Review Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          comment-summary-in-pr: always

  check-outdated:
    name: Check Outdated Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Check for outdated npm packages
        run: |
          npm outdated || true
          echo "ℹ️ Check output above for outdated npm packages"

      - name: Check for outdated pip packages
        run: |
          pip install pip-check
          pip-check || true
          echo "ℹ️ Check output above for outdated Python packages"
